### ISSUE TITLE
Integration with VLC?

### ISSUE THREAD

**Issue by jakebiesinger** [LeonNicholls/Fling#1]
Hi!

So VLC has a nice option to transcode video on-the-fly to many different formats including h.264+mp3 in an .mp4 container-- so completely supported by the chromecast.  VLC handles creating the HTTP server already. I don't know if they have a Java compatible API, but it seems like your drag-n-drop interface could just call up vlc with something like: 

```
:sout=#transcode{vcodec=h264,vb=0,scale=0,acodec=mpga,ab=128,channels=2,samplerate=44100}:http{dst=:8080/current_movie.mp4} :sout-keep
```

that is, transcode to h.264+mp3, output to `http://<my_ip_address>:8080/current_movie.mp4`.  Just point your chromecast there and you should stream it down, yes?

**Comment by LeonNicholls** [comment]
Using vlcj (http://www.capricasoftware.co.uk/projects/vlcj/index.html), I get the following error:

stream_out_standard stream out error: mov and mp4 mux are only valid with file output

**Comment by jakebiesinger** [comment]
Ah, bummer. There was no error message when I set up the stream and my browser started downloading something... I didn't wait for the whole move to download. So perhaps muxing this way is a no-go.

The available HTTP streams are listed here:  http://www.videolan.org/streaming-features.html. The other option is VP8/WebM but I don't see any mention on that page...

The message makes it sound like it's just a container issue so maybe you can stick h.264 video into a different container?

**Comment by LeonNicholls** [comment]
I'm not a VLC expert. If you can figure out what I need to send to VLC, I will code that.

**Comment by jakebiesinger** [comment]
I'm no expert either... but VLC can stream the webm format just fine.  Try this:

```
:sout=#transcode{vcodec=VP80,vb=2000,width=800,acodec=vorb,ab=128,channels=2,samplerate=44100}:http{mux=webm,dst=:8087/cast.webm} :sout-keep
```

That should produce a proper webm-formatted stream (chrome plays it fine; don't know about the chromecast).  Stuff to mess with might include:
-  `width=800` which is the output resolution width (maybe try `=540` to simulate casting a medium quality tab?)
-  `vb=2000` which is the video bitrate (lower for lower-quality)
-  `dst=:8087/cast.webm` which specifies the port to play on (8087) and the url (so `http://192.168.0.12:8087/cast.webm` opens up the stream on my machine.

Encoding on-the-fly is quite intensive, unfortunately. The video plays beautifully but my quad-core Xeon sits at ~5.7 load average.  I suppose converting them in advance might be in order. Then I could just cast the h.264 files as you're doing now.

**Comment by jakebiesinger** [comment]
Setting `width=540` and `vb=1000` still looks good but drops the load down to 1.6, which I think would be pretty reasonable for most.

**Comment by LeonNicholls** [comment]
That works! I'll do more testing, then check the code in.

**Comment by jakebiesinger** [comment]
Great!  I'm sure XBMC et al. will eventually have similar functionality but it'd be great to have a lightweight drag-n-drop transcoder/player. I'll try it out and give feedback tonight/whenever you push.

**Comment by LeonNicholls** [comment]
I think I need to make the settings configurable. Probably will check in tomorrow.

**Comment by jakebiesinger** [comment]
There's a lot you could do to expand... transcode/not transcode, transcode settings, you could queue up several items, etc.  Hope to play with it soon :+1:.

**Comment by LeonNicholls** [comment]
I decided to keep the settings simple. I have updated the readme with details. I have checked in the code. I have only tested the code on OS X.
