### ISSUE TITLE
Debugging output causes console beeps in Windows

### ISSUE THREAD

**Issue by davidcroda** [LeonNicholls/Fling#15]
This isn't really an issue, so much as a question.  When transcoding media, there is at on of console output with strange characters, along the lines of

write(42): {���E�~zs�.7e�xbn�.!<�B]Q� 9}�hDw�.!)�}

On windows, this is creating beeps for certain characters it can't interpret.

I can't seem to figure out where this logging output is coming from.  Can you point me in the right direction?

**Comment by LeonNicholls** [comment]
If you simply run the jar file by double-clicking it in the file explorer, the debug output won't be generated and you won't get these sounds.

**Comment by davidcroda** [comment]
Ok, thanks for the work around.  Even so, do you know where that logging is coming from or what it's related to? It's driving me a bit crazy. I've tried searching for the "write" string as well as the "send frame" and "matched frame" to no avail.  Is it VLCJ output?

**Comment by davidcroda** [comment]
Never mind, I found it right after asking! It is coming from the debug setting on the WebSocketClient.  Setting WebSocketImpl.DEBUG = false; stopped it.  Thanks for the awesome app!
