### ISSUE TITLE
Problems streaming to network

### ISSUE THREAD

**Issue by 4C3** [LeonNicholls/Fling#19]
First of all, I wanted to thank you a lot for this software. Chromecast was starting to be useless without this useful software. 

Secondly, I am unable to stream local files with the API key as well. I drag the file, but nothing happens on the device. Here is my error log. Could anyone look and suggest possible cause of errors?

java -jar fling.jar 7add939c-9f00-4a0a-9244-d7ec4f9163dc
Fling: Fling version 0.6
Fling: Linux
Fling: VLC available
Fling: App ID: 7add939c-9f00-4a0a-9244-d7ec4f9163dc
Fling: set to system default LaF
Fling: createAndShowGUI
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FlingFrame: Started web server on port 8080
Oct 08, 2013 10:32:55 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Starting client on address /239.255.255.250
Oct 08, 2013 10:32:55 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Broadcast client thread starting.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
FileDrop: Hierarchy changed.
FileDrop: Drop target added to component.
BroadcastDiscoveryClient: response=HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
DATE: Wed, 09 Oct 2013 03:32:57 GMT
EXT:
LOCATION: http://192.168.1.11:8008/ssdp/device-desc.xml
OPT: "http://schemas.upnp.org/upnp/1/0/"; ns=01
01-NLS: 9149b496-1dd2-11b2-bcc7-b1a1c04cf3a8
SERVER: Linux/3.8.13, UPnP/1.0, Portable SDK for UPnP devices/1.6.18
X-User-Agent: redsonic
ST: urn:dial-multiscreen-org:service:dial:1
USN: uuid:765a6788-ec22-b460-9b6b-bf6fd82b59b3::urn:dial-multiscreen-org:service:dial:1
BOOTID.UPNP.ORG: 2
CONFIGID.UPNP.ORG: 1

BroadcastDiscoveryClient: tokens.length=13
FlingFrame: location=http://192.168.1.11:8008/ssdp/device-desc.xml
FlingFrame: appsUrl=http://192.168.1.11:8008/apps/
FlingFrame: modelName=Eureka Dongle
FlingFrame: ChromeCast device found: 192.168.1.11
FlingFrame: size=1
Oct 08, 2013 10:33:10 PM com.entertailion.java.fling.Log i
INFO: BroadcastDiscoveryClient: Exiting client loop.
FileDrop: dragEnter event.
FileDrop: normal border saved.
FileDrop: drag border set.
FileDrop: event accepted.
FileDrop: dragEnter event.
FileDrop: normal border saved.
FileDrop: drag border set.
FileDrop: event accepted.
FileDrop: drop event.
FileDrop: file list accepted.
DragHereIcon: /home/artemis/Videos/intouchazt.avi
FlingFrame: sendMediaUrl=/home/artemis/Videos/intouchazt.avi
FlingFrame: Available port for VLC: 8081
FlingFrame: prefix=192.
FlingFrame: interface=wlan0
FlingFrame: address=/fe80:0:0:0:213:2ff:fed5:31f%3
FlingFrame: address=/192.168.1.2
FlingFrame: networkAddress=/192.168.1.2
FlingFrame: url=http://192.168.1.2:8081/cast.webm
RampClient: device=http://192.168.1.11:8008
RampClient: apps url=http://192.168.1.11:8008/apps/
RampClient: get response code=200
RampClient: lastUrl=http://192.168.1.11:8008/apps/00000000-0000-0000-0000-000000000000
RampClient: get response=<?xml version="1.0" encoding="UTF-8"?>
<service xmlns="urn:dial-multiscreen-org:schemas:dial">
  <name>00000000-0000-0000-0000-000000000000</name>
  <options allowStop="true"/>
  <state>running</state>
  <link rel="run" href="web-4"/>
  <servicedata xmlns="urn:chrome.google.com:cast">
    <connectionSvcURL>http://192.168.1.11:8008/connection/00000000-0000-0000-0000-000000000000</connectionSvcURL>
    <protocols>
      <protocol>com.google.chromecast.home</protocol>
    </protocols>
  </servicedata>
  <activity-status xmlns="urn:chrome.google.com:cast">
    <description>Chromecast Home screen</description>
  </activity-status>
</service>

RampClient: Content-Type=application/xml
RampClient: Content-Length=661
RampClient: delete response code=200
RampClient: delete response=
RampClient: get response code=404
RampClient: get response=
FileDrop: drop complete.
FileDrop: normal border restored.

Thanks a lot!

**Comment by LeonNicholls** [comment]
You need to put your app id in the receiver HTML file.

**Comment by 4C3** [comment]
I apologize if this is a dumb question, but we have to have a webserver with index.html or did you mean we have to compile Fling from source and have the app id modified before we compile ?

**Comment by LeonNicholls** [comment]
Yes, I was referring to the index.html file on your web server. It needs to be edited to include your app id.
