### ISSUE TITLE
Getting around the local encoding

### ISSUE THREAD

**Issue by ErwinP** [LeonNicholls/Fling#25]
First, mister Nicholls, a big thank you for releasing this application as open source and for providing so much feedback.

Now that I had it working (it wasn't explicitly said that one needs to run an http server with the receiver html - but finding it myself makes the glory even bigger), I noticed that my computer is in fact too old to transcode it. The CPU shoots to 100 percent, and the video is lagging.

I remembered however that Koushik Dutta succeeded in something similar with android as a platform, and remembered that he was talking about encoding/decoding. I've looked it up, a here's the post:
https://plus.google.com/110558071969009568835/posts/5fWK26rqitc

I speaks for itself that I have no experience on this stuff, so it could well be that I'm talking big rubbish here. However, I wanted to know if an implementation of this kind in Fling in somehow possible? If not, would you be so kind to give a more in-depth view on why - just out of curiousity on my side?

Thank you in advance for your answer,
Erwin

**Comment by LeonNicholls** [comment]
His solution only works for video formats directly supported by the Chromecast device. Other formats need to be encoded.
